CREATE DATABASE CRUD

USE CRUD

CREATE TABLE USUARIOS(
ID_USUARIOS INT IDENTITY(1,1),
NOMBRE VARCHAR(15),
EDAD INT,
CORREO VARCHAR(MAX),
FECHA_NACIMIENTO DATE
)

--PROCEDURES PARA CARGAR LA CARGA DE REGISTRO EN EL INICIO

CREATE PROCEDURE SP_LOAD
AS BEGIN
SELECT * FROM USUARIOS
END

-- PROCEDIMIENTOS PARA EL CRUD CREAR
CREATE PROCEDURE SP_CREATE
@NOMBRE VARCHAR(15),
@EDAD INT,
@CORREO VARCHAR(MAX),
@FECHA_NACIMIENTO DATE
AS BEGIN
INSERT INTO USUARIOS VALUES (@NOMBRE, @EDAD, @CORREO, @FECHA_NACIMIENTO)
END


-- PROCEDIMIENTOS PARA EL CRUD LEER
CREATE PROCEDURE SP_READ
@ID INT
AS BEGIN
SELECT * FROM USUARIOS WHERE ID_USUARIOS = @ID
END


-- PROCEDIMIENTOS PARA EL CRUD ACTUALIZAR
CREATE PROCEDURE SP_UPDATE
@ID INT,
@NOMBRE VARCHAR(15),
@EDAD INT,
@CORREO VARCHAR(MAX),
@FECHA_NACIMIENTO DATE
AS BEGIN
UPDATE USUARIOS SET NOMBRE = @NOMBRE, EDAD = @EDAD, CORREO=@CORREO,
FECHA_NACIMIENTO = @FECHA_NACIMIENTO WHERE ID_USUARIOS = @ID
END


-- PROCEDIMIENTOS PARA EL CRUD ELIMINAR
CREATE PROCEDURE SP_ELIMINAR
@ID INT
AS BEGIN
DELETE FROM USUARIOS WHERE ID_USUARIOS = @ID
END


SELECT * FROM USUARIOS
